import { Product } from "@cf/shared/types/product";

const catTshirts = {
  id: "cat_tshirts",
  slug: "t-shirts",
  name: "T-Shirts",
  nameEn: "T-Shirts",
  nameAr: "تي شيرت",
  order: 1,
};

const catHoodies = {
  id: "cat_hoodies",
  slug: "hoodies",
  name: "Hoodies",
  nameEn: "Hoodies & Sweatshirts",
  nameAr: "هوديز",
  order: 2,
};

const catBottoms = {
  id: "cat_bottoms",
  slug: "bottoms",
  name: "Pantalons & Shorts",
  nameEn: "Bottoms",
  nameAr: "بناطيل",
  order: 3,
};

const catOuterwear = {
  id: "cat_outerwear",
  slug: "outerwear",
  name: "Vestes & Manteaux",
  nameEn: "Outerwear",
  nameAr: "ملابس خارجية",
  order: 4,
};

const defaultVariants = (prefix: string) => [
  { id: `${prefix}_s`, name: "S", optionType: "size" as const, priceModifier: 0, stockQuantity: 25 },
  { id: `${prefix}_m`, name: "M", optionType: "size" as const, priceModifier: 0, stockQuantity: 40 },
  { id: `${prefix}_l`, name: "L", optionType: "size" as const, priceModifier: 0, stockQuantity: 30 },
  { id: `${prefix}_xl`, name: "XL", optionType: "size" as const, priceModifier: 0, stockQuantity: 15 },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod_1",
    sanityId: "sanity_1",
    slug: "comunity-oversized-tshirt-black",
    name: "T-Shirt Oversized Com.unity - Noir",
    nameEn: "Com.unity Oversized T-Shirt - Black",
    nameAr: "تي شيرت Com.unity واسع - أسود",
    shortDescription: "T-shirt oversized premium fabriqué en coton lourd 240 GSM.",
    description: "Un t-shirt oversized haut de gamme arborant le logo Com.unity brodé au centre. Coupe décontractée, coutures renforcées et tissu robuste 240 GSM pour un confort et une longévité ultimes.",
    price: 85.000,
    sku: "HU-TSH-001",
    mainImage: "/products/22848E29-9C2D-4397-99B7-7336249C7FAD.png",
    images: [
      { url: "/products/22848E29-9C2D-4397-99B7-7336249C7FAD.png", alt: "Com.unity Oversized T-Shirt Black", width: 800, height: 800 }
    ],
    category: catTshirts,
    brand: "HUMAN.UNITY",
    badge: "bestseller",
    rating: 4.9,
    reviewCount: 152,
    variants: defaultVariants("opt_tsb"),
    stockQuantity: 110,
    isActive: true,
    isWholesale: false,
    tags: ["Oversized", "Coton Lourd", "Broderie", "Noir"],
    metadata: {
      weight: "240 GSM",
      fabric: "100% Coton",
      fit: "Oversized",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_2",
    sanityId: "sanity_2",
    slug: "comunity-oversized-tshirt-white",
    name: "T-Shirt Oversized Com.unity - Blanc",
    nameEn: "Com.unity Oversized T-Shirt - White",
    nameAr: "تي شير t Com.unity واسع - أبيض",
    shortDescription: "T-shirt oversized premium fabriqué en coton lourd 240 GSM.",
    description: "Version blanche du t-shirt oversized signature Com.unity. Conçu pour le quotidien des créateurs, combinant confort décontracté et durabilité premium grâce à son coton épais.",
    price: 85.000,
    sku: "HU-TSH-002",
    mainImage: "/products/71CA9D12-CCCB-4DCA-BBC4-FA9A4B5C054C.png",
    images: [
      { url: "/products/71CA9D12-CCCB-4DCA-BBC4-FA9A4B5C054C.png", alt: "Com.unity Oversized T-Shirt White", width: 800, height: 800 }
    ],
    category: catTshirts,
    brand: "HUMAN.UNITY",
    badge: "new",
    rating: 4.8,
    reviewCount: 94,
    variants: defaultVariants("opt_tsw"),
    stockQuantity: 110,
    isActive: true,
    isWholesale: false,
    tags: ["Oversized", "Coton Lourd", "Broderie", "Blanc"],
    metadata: {
      weight: "240 GSM",
      fabric: "100% Coton",
      fit: "Oversized",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_3",
    sanityId: "sanity_3",
    slug: "one-mission-hoodie-brown",
    name: "Sweat à Capuche One Mission - Marron",
    nameEn: "One Mission Hoodie - Brown",
    nameAr: "هودي One Mission - بني",
    shortDescription: "Hoodie lourd de 400 GSM avec coupe boxy et sérigraphie au dos.",
    description: "Un sweat à capuche lourd haut de gamme conçu pour durer. Molleton 400 GSM très épais, coupe boxy rétro, sans cordon de serrage pour un look épuré, avec la sérigraphie artistique 'One Mission' à l'arrière.",
    price: 145.000,
    comparePrice: 165.000,
    sku: "HU-HOD-003",
    mainImage: "/products/883278D9-F82F-494D-B604-2F14D3603AB4.png",
    images: [
      { url: "/products/883278D9-F82F-494D-B604-2F14D3603AB4.png", alt: "One Mission Hoodie Brown", width: 800, height: 800 }
    ],
    category: catHoodies,
    brand: "HUMAN.UNITY",
    badge: "limited",
    rating: 5.0,
    reviewCount: 88,
    variants: defaultVariants("opt_hob"),
    stockQuantity: 110,
    isActive: true,
    isWholesale: false,
    tags: ["Heavyweight", "Boxy Fit", "Sérigraphie", "Marron"],
    metadata: {
      weight: "400 GSM",
      fabric: "100% Coton Molleton",
      fit: "Boxy Fit",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_4",
    sanityId: "sanity_4",
    slug: "one-mission-hoodie-black",
    name: "Sweat à Capuche One Mission - Noir",
    nameEn: "One Mission Hoodie - Black",
    nameAr: "هودي One Mission - أسود",
    shortDescription: "Hoodie lourd de 400 GSM avec coupe boxy et sérigraphie au dos.",
    description: "L'indispensable hoodie noir lourd en coton molletonné de 400 GSM. Coupe boxy moderne, capuche doublée, et impression sérigraphique à l'arrière portant le message d'unité.",
    price: 145.000,
    sku: "HU-HOD-004",
    mainImage: "/products/22E54FA2-09E7-4C49-BD58-5B8286BED6CC.png",
    images: [
      { url: "/products/22E54FA2-09E7-4C49-BD58-5B8286BED6CC.png", alt: "One Mission Hoodie Black", width: 800, height: 800 }
    ],
    category: catHoodies,
    brand: "HUMAN.UNITY",
    badge: "bestseller",
    rating: 4.9,
    reviewCount: 210,
    variants: defaultVariants("opt_hok"),
    stockQuantity: 110,
    isActive: true,
    isWholesale: false,
    tags: ["Heavyweight", "Boxy Fit", "Sérigraphie", "Noir"],
    metadata: {
      weight: "400 GSM",
      fabric: "100% Coton Molleton",
      fit: "Boxy Fit",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_5",
    sanityId: "sanity_5",
    slug: "akhira-windbreaker-jacket",
    name: "Veste Coupe-Vent Akhira",
    nameEn: "Akhira Windbreaker Jacket",
    nameAr: "جاكيت واقي من الرياح Akhira",
    shortDescription: "Veste imperméable coupe-vent technique avec finitions ajustables.",
    description: "Un coupe-vent technique alliant style urbain et protection contre les intempéries. Tissu technique imperméable de qualité supérieure, fermeture éclair étanche, cordons de serrage ajustables à la capuche et à la taille.",
    price: 175.000,
    sku: "HU-OUT-005",
    mainImage: "/products/1517E8D4-72BF-4BA4-B415-C01FA6CE9C93.png",
    images: [
      { url: "/products/1517E8D4-72BF-4BA4-B415-C01FA6CE9C93.png", alt: "Akhira Windbreaker Jacket", width: 800, height: 800 }
    ],
    category: catOuterwear,
    brand: "HUMAN.UNITY",
    badge: "new",
    rating: 4.7,
    reviewCount: 35,
    variants: defaultVariants("opt_akw"),
    stockQuantity: 110,
    isActive: true,
    isWholesale: false,
    tags: ["Technique", "Imperméable", "Ajustable", "Outdoor"],
    metadata: {
      material: "Nylon Technique",
      lining: "Mesh respirant",
      waterResistance: "10000mm",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_6",
    sanityId: "sanity_6",
    slug: "comunity-heavyweight-sweatpants",
    name: "Pantalon de Jogging Com.unity",
    nameEn: "Com.unity Heavyweight Sweatpants",
    nameAr: "بنطال رياضي Com.unity ثقيل",
    shortDescription: "Pantalon de jogging lourd en molleton de 380 GSM.",
    description: "Conçu pour être assorti à nos sweats à capuche, ce pantalon de jogging en coton molletonné lourd de 380 GSM offre une silhouette structurée mais confortable. Poches zippées discrètes et taille élastique ajustable.",
    price: 110.000,
    comparePrice: 125.000,
    sku: "HU-BOT-006",
    mainImage: "/products/card 1.png",
    images: [
      { url: "/products/card 1.png", alt: "Com.unity Heavyweight Sweatpants", width: 800, height: 800 }
    ],
    category: catBottoms,
    brand: "HUMAN.UNITY",
    badge: "bestseller",
    rating: 4.8,
    reviewCount: 125,
    variants: defaultVariants("opt_csw"),
    stockQuantity: 110,
    isActive: true,
    isWholesale: false,
    tags: ["Heavyweight", "Loose Fit", "Poches Zippées", "Gris"],
    metadata: {
      weight: "380 GSM",
      fabric: "100% Coton Molleton",
      fit: "Loose Fit",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_7",
    sanityId: "sanity_7",
    slug: "akhira-cargo-pants",
    name: "Pantalon Cargo Akhira",
    nameEn: "Akhira Cargo Pants",
    nameAr: "بنطال كارغو Akhira",
    shortDescription: "Pantalon cargo technique avec poches utilitaires.",
    description: "Un pantalon cargo de style utilitaire moderne avec multiples poches de rangement, des chevilles ajustables par cordon et une ceinture intégrée pour un ajustement parfait.",
    price: 130.000,
    sku: "HU-BOT-007",
    mainImage: "/products/26646BED-F20A-46D4-845E-4F2A4E3EAF41.png",
    images: [
      { url: "/products/26646BED-F20A-46D4-845E-4F2A4E3EAF41.png", alt: "Akhira Cargo Pants", width: 800, height: 800 }
    ],
    category: catBottoms,
    brand: "HUMAN.UNITY",
    badge: "new",
    rating: 4.6,
    reviewCount: 42,
    variants: defaultVariants("opt_akc"),
    stockQuantity: 110,
    isActive: true,
    isWholesale: false,
    tags: ["Cargo", "Technique", "Utility", "Noir"],
    metadata: {
      fabric: "Nylon Ripstop",
      pockets: "6 Poches",
      fit: "Relaxed Fit",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_8",
    sanityId: "sanity_8",
    slug: "comunity-knit-beanie",
    name: "Bonnet en Maille Com.unity",
    nameEn: "Com.unity Knit Beanie",
    nameAr: "قبعة Com.unity صوفية",
    shortDescription: "Bonnet en maille côtelée douce avec patch logo signature.",
    description: "Un bonnet classique à revers en maille côtelée ultra-douce. Doté du patch tissé HUMAN.UNITY à l'avant, c'est l'accessoire parfait pour compléter vos tenues de mi-saison.",
    price: 45.000,
    sku: "HU-ACC-008",
    mainImage: "/products/CF817762-DE5F-4EC2-8110-BC17CEF3BDAA.png",
    images: [
      { url: "/products/CF817762-DE5F-4EC2-8110-BC17CEF3BDAA.png", alt: "Com.unity Knit Beanie", width: 800, height: 800 }
    ],
    category: catOuterwear,
    brand: "HUMAN.UNITY",
    badge: "organic",
    rating: 4.9,
    reviewCount: 61,
    variants: [
      { id: "opt_beanie_one", name: "Taille Unique", optionType: "size" as const, priceModifier: 0, stockQuantity: 150 }
    ],
    stockQuantity: 150,
    isActive: true,
    isWholesale: false,
    tags: ["Accessoire", "Maille", "Beanie", "Noir"],
    metadata: {
      fabric: "100% Acrylique Doux",
      fit: "One Size",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_9",
    sanityId: "sanity_9",
    slug: "one-mission-crewneck-grey",
    name: "Sweat Crewneck One Mission - Gris",
    nameEn: "One Mission Crewneck - Grey",
    nameAr: "سويت شيرت One Mission - رمادي",
    shortDescription: "Sweat col rond en molleton lourd 360 GSM.",
    description: "Un sweat col rond intemporel confectionné dans un molleton de coton lourd gris chiné de 360 GSM. Intérieur brossé pour une douceur optimale et finitions en bord-côte robuste.",
    price: 120.000,
    sku: "HU-HOD-009",
    mainImage: "/products/FA148DB6-835D-4AF5-9CE6-639BD0A9DAE5.png",
    images: [
      { url: "/products/FA148DB6-835D-4AF5-9CE6-639BD0A9DAE5.png", alt: "One Mission Crewneck Grey", width: 800, height: 800 }
    ],
    category: catHoodies,
    brand: "HUMAN.UNITY",
    badge: "new",
    rating: 4.8,
    reviewCount: 38,
    variants: defaultVariants("opt_crg"),
    stockQuantity: 110,
    isActive: true,
    isWholesale: false,
    tags: ["Crewneck", "Gris Chiné", "Coton Lourd", "Minimaliste"],
    metadata: {
      weight: "360 GSM",
      fabric: "80% Coton / 20% Polyester",
      fit: "Regular Fit",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_10",
    sanityId: "sanity_10",
    slug: "humanunity-graphic-tee-vintage-black",
    name: "T-Shirt Graphique Human Unity - Noir Délavé",
    nameEn: "Human Unity Graphic Tee - Vintage Black",
    nameAr: "تي شيرت Human Unity رسم - أسود معتق",
    shortDescription: "T-shirt graphique de style vintage délavé à l'acide.",
    description: "T-shirt en coton épais doté d'un délavage à l'acide vintage unique pour un look rétro usé. Comprend un grand motif graphique artistique imprimé sur la poitrine représentant la connexion humaine.",
    price: 90.000,
    sku: "HU-TSH-010",
    mainImage: "/products/B5CADD35-C109-4343-AC23-0FF14E4449B0.png",
    images: [
      { url: "/products/B5CADD35-C109-4343-AC23-0FF14E4449B0.png", alt: "Human Unity Graphic Tee Vintage Black", width: 800, height: 800 }
    ],
    category: catTshirts,
    brand: "HUMAN.UNITY",
    badge: "sale",
    rating: 4.9,
    reviewCount: 77,
    variants: defaultVariants("opt_gvb"),
    stockQuantity: 110,
    isActive: true,
    isWholesale: false,
    tags: ["Vintage", "Graphique", "Délavé", "Noir"],
    metadata: {
      weight: "220 GSM",
      fabric: "100% Coton Premium",
      fit: "Relaxed Fit",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_11",
    sanityId: "sanity_11",
    slug: "humanunity-heavyweight-hoodie-off-white",
    name: "Sweat à Capuche Lourd - Blanc Cassé",
    nameEn: "Human Unity Heavyweight Hoodie - Off-White",
    nameAr: "هودي ثقيل - أبيض طبيعي",
    shortDescription: "Sweat à capuche très lourd 420 GSM en coton biologique blanc cassé.",
    description: "Le summum du confort. Ce sweat à capuche blanc cassé est confectionné dans un coton biologique ultra-épais de 420 GSM. Coupe boxy structurée avec broderie ton sur ton minimaliste.",
    price: 155.000,
    sku: "HU-HOD-011",
    mainImage: "/products/DD11EABC-6B61-42F0-AE2F-312198A74038.png",
    images: [
      { url: "/products/DD11EABC-6B61-42F0-AE2F-312198A74038.png", alt: "Human Unity Heavyweight Hoodie Off-White", width: 800, height: 800 }
    ],
    category: catHoodies,
    brand: "HUMAN.UNITY",
    badge: "bestseller",
    rating: 5.0,
    reviewCount: 148,
    variants: defaultVariants("opt_how"),
    stockQuantity: 110,
    isActive: true,
    isWholesale: false,
    tags: ["Heavyweight", "Coton Bio", "Blanc Cassé", "Broderie"],
    metadata: {
      weight: "420 GSM",
      fabric: "100% Coton Biologique",
      fit: "Boxy Fit",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_12",
    sanityId: "sanity_12",
    slug: "comunity-zip-up-hoodie",
    name: "Sweat à Capuche Zippé Com.unity",
    nameEn: "Com.unity Zip-Up Hoodie",
    nameAr: "هودي بسحاب Com.unity",
    shortDescription: "Sweat à capuche zippé avec fermeture double curseur YKK.",
    description: "Un sweat à capuche entièrement zippé offrant une grande polyvalence de style. Doté d'une fermeture éclair double curseur YKK en métal argenté et d'un tissu molletonné brossé chaud.",
    price: 150.000,
    sku: "HU-HOD-012",
    mainImage: "/products/CA4016B4-69C0-4F41-B01A-420CA33B9B40.png",
    images: [
      { url: "/products/CA4016B4-69C0-4F41-B01A-420CA33B9B40.png", alt: "Com.unity Zip-Up Hoodie", width: 800, height: 800 }
    ],
    category: catHoodies,
    brand: "HUMAN.UNITY",
    badge: "new",
    rating: 4.7,
    reviewCount: 29,
    variants: defaultVariants("opt_zuh"),
    stockQuantity: 110,
    isActive: true,
    isWholesale: false,
    tags: ["Zip-Up", "YKK", "Double Curseur", "Noir"],
    metadata: {
      weight: "360 GSM",
      fabric: "100% Coton Molleton",
      fit: "Relaxed Fit",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_13",
    sanityId: "sanity_13",
    slug: "akhira-fleece-jacket",
    name: "Veste en Polaire Akhira",
    nameEn: "Akhira Fleece Jacket",
    nameAr: "جاكيت صوف Akhira",
    shortDescription: "Veste chaude en polaire épaisse sherpa avec poches contrastées.",
    description: "Une veste en polaire de type Sherpa épaisse conçue pour vous garder au chaud pendant les mois les plus froids. Finitions contrastées en nylon résistant à l'eau sur le col et la poche poitrine.",
    price: 165.000,
    sku: "HU-OUT-013",
    mainImage: "/products/E2A4FC45-876E-4261-8731-CF3D5E8D77F2.png",
    images: [
      { url: "/products/E2A4FC45-876E-4261-8731-CF3D5E8D77F2.png", alt: "Akhira Fleece Jacket", width: 800, height: 800 }
    ],
    category: catOuterwear,
    brand: "HUMAN.UNITY",
    badge: "limited",
    rating: 4.9,
    reviewCount: 54,
    variants: defaultVariants("opt_afj"),
    stockQuantity: 110,
    isActive: true,
    isWholesale: false,
    tags: ["Polaire Sherpa", "Outdoor", "Chaud", "Style Urbain"],
    metadata: {
      fabric: "100% Polyester Sherpa",
      pockets: "3 Poches Zippées",
      fit: "Regular Fit",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_14",
    sanityId: "sanity_14",
    slug: "comunity-coach-jacket",
    name: "Veste Coach Com.unity",
    nameEn: "Com.unity Coach Jacket",
    nameAr: "سترة كوتش Com.unity",
    shortDescription: "Veste style coach classique en nylon résistant à l'eau.",
    description: "Une veste d'entraîneur classique revisitée pour la rue. Fabriquée dans un nylon résistant à l'eau avec fermeture par boutons-pression mats et cordon de serrage au bas pour ajuster la silhouette.",
    price: 160.000,
    sku: "HU-OUT-014",
    mainImage: "/products/D77DD97E-EC0D-44C4-8FF7-960E13015748.png",
    images: [
      { url: "/products/D77DD97E-EC0D-44C4-8FF7-960E13015748.png", alt: "Com.unity Coach Jacket", width: 800, height: 800 }
    ],
    category: catOuterwear,
    brand: "HUMAN.UNITY",
    badge: "new",
    rating: 4.8,
    reviewCount: 22,
    variants: defaultVariants("opt_ccj"),
    stockQuantity: 110,
    isActive: true,
    isWholesale: false,
    tags: ["Coach Jacket", "Nylon", "Boutons Pression", "Noir"],
    metadata: {
      fabric: "100% Nylon Oxford",
      lining: "Doublure satinée",
      fit: "Regular Fit",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_15",
    sanityId: "sanity_15",
    slug: "one-mission-sweatshorts",
    name: "Short de Jogging One Mission",
    nameEn: "One Mission Sweatshorts",
    nameAr: "شورت رياضي One Mission",
    shortDescription: "Short de jogging confortable en coton lourd 340 GSM.",
    description: "Le short de repos ultime. Fabriqué dans le même coton molletonné lourd que nos crewnecks, avec une taille élastique confortable, un cordon de serrage intérieur et une poche arrière plaquée.",
    price: 75.000,
    comparePrice: 85.000,
    sku: "HU-BOT-015",
    mainImage: "/products/DCDA223D-5A33-4A75-9624-E88A274B6E62.png",
    images: [
      { url: "/products/DCDA223D-5A33-4A75-9624-E88A274B6E62.png", alt: "One Mission Sweatshorts", width: 800, height: 800 }
    ],
    category: catBottoms,
    brand: "HUMAN.UNITY",
    badge: "sale",
    rating: 4.7,
    reviewCount: 46,
    variants: defaultVariants("opt_oms"),
    stockQuantity: 110,
    isActive: true,
    isWholesale: false,
    tags: ["Sweatshorts", "Coton Lourd", "Confort", "Gris"],
    metadata: {
      weight: "340 GSM",
      fabric: "100% Coton",
      fit: "Relaxed Fit",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
